backend:
  name: git-gateway
  branch: main
media_folder: "images/uploads"
public_folder: "/images/uploads"
collections:
  - name: "site"
    label: "Contenu du site"
    files:
      - name: "home"
        label: "Page d'accueil"
        file: "content/home.md"
        fields:
          - { label: "Titre", name: "title", widget: "string" }
          - { label: "Short description", name: "short_description", widget: "text" }
          - { label: "Description", name: "description", widget: "markdown" }
          - label: "Images du carousel"
            name: "carousel"
            widget: "list"
            field: { label: "Image", name: "image", widget: "image" }
          - label: "Équipements"
            name: "amenities"
            widget: "list"
            field: { label: "Élément", name: "item", widget: "string" }
          - { label: "Localisation", name: "location", widget: "string" }
